import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import FormSendData from "../components/FormSendData";
import HomePage from "../components/HomePage";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage />
      {/* <main className={styles.main}>
        <FormSendData/>
      </main> */}
    </div>
  );
};

export default Home;
